var stories = {
	"Benson" : 	{"title" : "The Ballad of Benson",
				 "body"  : "Ever since he was <age>, Benson has dreamed of being as <adjective> as his idol, <actor-or-actress>. He thinks with great <Emotion> about having such picture-perfect <Body-Part>(s) every day. It's no wonder he buys his <Article(s)-OF-clothing> similar to the one(s) seen in their films.\nBut he still looks way too <adjective> that way, according to most people in <city>. In fact, the <religious-group> have filed several complaints about this <ordinary-adjective> behavior. Someone should break the news to him, but the risk of making him feel <emotion> is far too great. It could ruin his status as the <number>'th highest rated teacher in town. (The highest-rated is, of course, <person's-name>.)\nDid you know that Marty Stepp spends most of his time at <place>? Perhaps he's hoping to be a <job-title> when he grows up. It's a shame he will never reach such a/an <adjective> position after having majored in the field of <area-of-study>."
				},
	"Clothes" : {"title" : "Gonna Pop Some Tags",
				 "body"  : "<Male-Name> has announced that his <adjective> clothing store in the heart of downtown <CITY> is having a/an <adjective> sale of all merchandise, including <unusual-adjective> suits and slightly irregular <plural-noun> available. Men's cable-knit <plural-noun>, only $15.99. Hand-woven Italian <plural-noun>, 1/2-price. Double- breasted cashmere <plural-noun>, $50.00. Genuine imported <Color> <adjective> shoes, <Exciting-adjective> handkerchiefs, and women's embroidered <plural-noun>, all at rock-bottom prices. This is a chance to get some really <Interesting-Adjective> bargains."
				},
	"Dance" : 	{"title" : "Move Over, Monster Mash",
			   	 "body"  : "Here's how you dance the Monstrosity. Stand with your feet together. Now, move your left foot <aDvErB> to the side. Now stamp your right foot <NUMBER> times and put your hands on your partner's <Plural-Noun>. Next, you both <verb> slowly to the right and bend your <body-part> backward. For the next eight counts, both of you <verb> <adverb> to the left. Next, you and your partner stand back to back and wiggle your <pluRAL-nOUN> and slap your <plural-noun> together. Don't forget to keep stamping your right foot. Now, face your partner again, put your <plural-noun> together and shout, \"<FUNNY-noise>!\" Now, <verb> backward and repeat the whole thing <Number> times. If you feel that you can't learn this dance, you can always <verB> the next one out."
			   	},
	"Tarzan" :  {"title" : "Lord of the Jungle",
				 "body"  : "One of the most <adjective> characters in fiction is named \"Tarzan of the <plural-noun>.\" Tarzan was raised by a/an <noun> and lives in the <adjective> jungle in the heart of darkest <place>. He spends most of his time eating <plural-noun> and swinging from tree to <noun>. Whenever he gets angry, he beats on his chest and says, \"<funny-noise>!\" This is his war cry. Tarzan always dresses in <adjective> shorts made from the skin of a/an <noun> and his best friend is a/an <adjective> chimpanzee named Cheetah. He is supposed to be able to speak to elephants and <plural-noun>. In the movies, Tarzan is played by <person's-name>."
				},
	"University" : {"title" : "Go Harvard!",
				    "body"  : "Our American universities offer students many <adjective> courses that will prepare them to become professional <plural-noun>. You can get a degree as a Bachelor of <plural-noun> or take a regular liberal <plural-noun> course. Or, if you want to become a/an <adjective> engineer, you can study <adjective> mathematics and differential <plural-noun>. Then, after <number> years, if you want to continue your studies you can write a/an <noun> and become a Dotor of <plural-noun>. When you get out into the <adjective> world, if you have a diploma from a university, you will be able to get a job easily as a/an <job-title> or even a/an <job-title>. If you don't have a dpiloma, you may have to take a job as a <noun>. Remember, it's important that you study hard in high school so you are able to do well on your college entrance <plural-noun>. It is true that \"a little learning is a/an <adjective> thing.\""
				},
	"Advice" :  {"title" : "A Few Wise Words",
				 "body"  : "When I was just <number> years old, I found a note from my father. It said: \"Son, I want you to know what I really think of you. You are <adjective>. When you were first born and I saw your <plural-body-parts> I knew right then that you would make me <emotion-adjective>. It's a big, <adjective> world out there and there will come a time when I won’t be here anymore. You must take life's issues one step at a time. Make sure you do your <noun>, be kind to others, take care of your <animal>, buy a nice used <noun> first before purchasing a brand new one, obey your <family-member> and handle peer pressure the smartest way possible. Don't <verb>, say no to <plural-noun>, don't drink and drive, find a nice <noun> to call your own, be great to her and son, never give up your <plural-noun>. Stay true to yourself and go for what you love. I know you want to become a/an <profession> some day, make me proud! I love you son. From, Dad\"\nThis is the best piece of advice I've ever gotten. I hope it helps you too!"
				},	
	"Crisis" :  {"title" : "How To Get Out of a Midlife Crisis",
				 "body"  : "So you're 40 years old and you're having a mid-life crisis. You can't get out of your bed in the morning and all you want to eat is <food>. What do you do? Follow these tips <adverb>. \n 1 ) Get yourself to a/an <profession>'s office immediately. \n 2 ) Let your close friends take you to <place> where you can <verb> and think about your life back at home. \n 3 ) Meditate outdoors, if possible, <number> times a day. \n 4 ) A dose of yoga will reawaken your inner <noun>. Take a deep breath, breathe out and relax on a <noun>. \n 5 ) Buy yourself a new <noun> because you're worth it. \n 6 ) Turn up the volume and listen to <music-genre> music as much as possible. \n 7 ) Meet someone new. This can help lift your spirit and make you feel <emotion>. \n 8 ) Volunteer at the <noun> store. It will help get your mind off things. \n 9 ) Go <activity>. Keeping your mind more active and less sluggish will make a great difference. \n 10 ) Talk to your <family-member>, go to a help group to talk about your feelings, or call 1-800-help-me-now. \n Good luck!" 
				},
	"Christmas" :  {"title" : "Holiday Cheer!",
				 "body"  : "Oh man, is it really beginning to look like Christmas! The <plural-noun> are twinkling, the snow is <verb-ending-with-ing>, and the fire in the <noun> is roaring! I’d love to eat some <plural-noun> today, maybe go <verb-ending-with-ing> at the ice rink- who knows? Unfortunately, my older brother got stuck in his <noun> because of the heavy snowfall- he seems quite <emotion-adjective> about it. I feel sorry for him, but oh well- on to a day of <verb-ending-with-ing> <plural-noun> and <verb-ending-with-ing>!"
				},	
	"Amazon" :  {"title" : "The Origins of Amazon",
				 "body"  : "When Amazon launched in 1995 as a website that only sold <plural-noun>, founder <name> had a vision for the company's <adjective> growth and ecommerce domination. He knew from the very beginning that he wanted Amazon to be a/an <adjective> store. In the early days of Amazon, a <noun> would tell the <place> every time someone made a purchase, and everyone would gather around to see if they knew the customer. It only took a few weeks before the <noun> would go off so frequently that they had to turn it off. In the first month of its launch, Amazon had already sold <plural-noun> to <plural-noun> in all 50 states and in <number> different countries. It is truly a story of <emotion>!"
				},	
	"Love" :  {"title" : "My Love Poem",
				 "body"  : "This love letter to <name>, I'm sending my heart. \nYour <adjective> face makes me never want to be apart. \nEvery time I see you <verb>, my heart skips a beat, \nCause without your <adjective> aroma, I am not complete. \nA/an <adjective> smile and a fragrance of a rose, \nThat being the best thing that has ever touched my nose. \nI can't help but turn <color> when I catch your eye, \nIt makes all the <plural-noun> in my stomach begin to fly. \nTake this <adjective> poem and give me a sign, \nTo you my dear, Please be mine. \nFrom, <name>"
				}
};
